// French: every interface string, by the same stable keys as English
// (js/localization/strings/en.js), registry-owned game copy included
// (universal movement, Launch, difficulty levels, stages, controls and each fighter's
// button names, translated here by key). A key missing here falls back to
// English; tests/interface/i18n.test.mjs fails if one is.

import { CONFIG } from '../../config.js';
import { formatList } from '../format.js';

export const FR = {
  'brand.title': CONFIG.title,

  'control.runLeft': 'Aller à gauche',
  'control.runRight': 'Aller à droite',
  'control.down': 'Bas',
  'control.jump': 'Saut',
  'control.extra_attack': 'Attaque supplémentaire',
  'control.transform': 'Transformation',
  'control.shield': 'Bouclier',
  'control.attack1': 'Attaque 1',
  'control.attack2': 'Attaque 2',
  'control.attack3': 'Attaque 3',
  'control.attack4': 'Attaque 4',
  'control.attack5': 'Attaque 5',
  'control.pause': 'Pause',
  'ability.0001.extra_attack': 'Coup de pied haut',
  'ability.0001.attack1': 'Direct',
  'ability.0001.attack2': 'Rouge',
  'ability.0001.attack3': 'Bleu maximal',
  'ability.0001.attack4': 'Vide infini',
  'ability.0001.attack5': 'Violet creux',
  'ability.0001.midair_attack1': 'Direct flottant',
  'ability.0001.midair_attack2': 'Coup de pied rouge',
  'ability.0001.midair_attack3': 'Bleu',
  'ability.0002.midair_attack1': 'Attaque à tête chercheuse',
  'ability.0002.midair_attack2': 'Attaque rebondissante',
  'ability.0002.midair_attack3': 'Tornade bleue',
  'ability.0002.extra_attack': 'Tourbillon',
  'ability.0002.attack1': 'Un-deux',
  'ability.0002.attack2': 'Coups de pied rapides',
  'ability.0002.attack3': 'Attaque tournoyante',

  'movement.summary': 'Le déplacement est le même pour tous : une course, des sauts, un sprint. Ce qui distingue chacun, ce sont ses coups.',
  'movement.run.name': 'Course',
  'movement.run.description': 'Pleine vitesse en un instant, demi-tour immédiat. La vitesse acquise se conserve à travers les sauts, les attaques et les atterrissages.',
  'movement.jump.name': 'Saut',
  'movement.jump.description': 'Une pression brève donne le saut normal ; maintenue un peu plus longtemps, le saut plus haut.',
  'movement.airJumps.name': 'Triple saut',
  'movement.airJumps.description': 'Deux sauts de plus en l’air. Atterrir ou être touché les rend.',
  'movement.fastFall.name': 'Chute rapide',
  'movement.fastFall.description': 'Maintenez Bas en tombant pour descendre plus vite.',
  'movement.dash.name': 'Sprint',
  'movement.dash.description': 'Appuyez sur Q/E, sur Select/View + gauche/droite à la manette, ou sur un bouton de mouvement pour un élan de vitesse. Une attaque ou un saut peut l’interrompre après un instant.',
  'movement.airDash.name': 'Sprint aérien',
  'movement.airDash.description': 'Le sprint en l’air, à l’horizontale, une fois avant de retoucher le sol.',

  'launch.pointSummary':
    'Le Point d’éjection part de 0. Chaque coup non bloqué ajoute ses dégâts et relance la récupération : ' +
    'après 2 secondes sans coup reçu, il baisse de 1 toutes les 0,5 secondes suivantes, jusqu’à 0 (premier point à 2,5 secondes). ' +
    'Les coups bloqués ne relancent pas ce délai. Plus il est élevé, plus l’éjection est forte. Il revient à 0 à la réapparition.',
  'launch.formula': 'Force d’éjection = Éjection de base × Point d’éjection',
  'launch.baseSummary':
    'Chaque coup a une Éjection de base de 0, 1, 2 ou 3. Les dégâts du coup s’ajoutent d’abord au Point d’éjection, ' +
    'puis le nouveau Point d’éjection est multiplié par l’Éjection de base.',
  'launch.base.0': 'Aucune éjection. Le Point d’éjection est multiplié par zéro.',
  'launch.base.1': 'Éjection normale. Utilise le Point d’éjection une fois.',
  'launch.base.2': 'Éjection double. Utilise deux fois le Point d’éjection.',
  'launch.base.3': 'Éjection triple. Utilise trois fois le Point d’éjection.',
  'launch.directionalSummary':
    'Chaque coup a aussi une Éjection directionnelle. Elle détermine où la force d’éjection envoie la cible, jamais sa puissance.',
  'launch.direction.none.name': 'Aucune',
  'launch.direction.none.description': 'Le coup inflige des dégâts, mais ne provoque aucune éjection directionnelle.',
  'launch.direction.horizontal.name': 'Horizontale',
  'launch.direction.horizontal.description': 'Éjecte dans le sens où va le coup.',
  'launch.direction.vertical.name': 'Verticale',
  'launch.direction.vertical.description': 'Éjecte vers le haut.',
  'launch.direction.reverseVertical.name': 'Verticale inversée',
  'launch.direction.reverseVertical.description': 'Éjecte vers le bas.',

  'difficulty.easy.name': 'Facile',
  'difficulty.easy.description': 'Réactions lentes. Laisse des ouvertures.',
  'difficulty.medium.name': 'Moyen',
  'difficulty.medium.description': 'Réactions et décisions équilibrées.',
  'difficulty.hard.name': 'Difficile',
  'difficulty.hard.description': 'Réactions rapides. Se défend et punit.',
  'difficulty.brutal.name': 'Brutal',
  'difficulty.brutal.description': 'Réactions vives. Décisions implacables.',

  'map.desert.name': 'Désert',
  'map.desert.tagline': 'Mesa de grès à l’heure dorée',
  'map.city.name': 'Ville',
  'map.city.tagline': 'Toit d’immeuble à la nuit tombée',

  'common.back': 'Retour',
  'common.selected': 'Sélectionné',
  'common.default': 'Par défaut',
  'common.retry': 'Réessayer',
  'common.loading': 'Chargement',
  'common.loadingName': 'Chargement de {name}',
  'common.assetsUnavailable': 'Ressources indisponibles',
  'common.spritesFailed': ({ names, where }) =>
    `Les sprites de ${formatList(names, 'fr')} n’ont pas pu être chargés. Vérifiez votre connexion et la présence des fichiers dans ${where}.`,
  'common.confirm': 'Confirmer',
  'common.cancel': 'Annuler',
  'common.close': 'Fermer',
  'common.noFighters': 'Aucun combattant disponible',
  'common.fighterUnavailable': 'Combattant indisponible',
  'common.fighterUnavailableMessage': 'Cette session ne peut pas commencer : un combattant nécessaire n’est pas disponible.',

  'hint.navigate': 'Naviguer',
  'hint.select': 'Sélectionner',
  'hint.back': 'Retour',
  'key.enter': 'Entrée',
  'key.esc': 'Échap',

  'screen.splash': 'Introduction',
  'screen.mode': 'Choix du mode',
  'screen.difficulty': 'Choix de la difficulté',
  'screen.character': 'Choix du combattant',
  'screen.quickCpu': 'Choix du CPU',
  'screen.map': 'Choix de l’arène',
  'screen.watchDifficulty': 'Mode Spectateur : choix de la difficulté',
  'screen.watchCpu1': 'Mode Spectateur : choix du CPU 1',
  'screen.watchCpu2': 'Mode Spectateur : choix du CPU 2',
  'screen.watchMap': 'Mode Spectateur : choix de l’arène',
  'screen.battle': 'Combat',
  'screen.practice': 'Terrain d’entraînement',
  'screen.discover': 'Découvrir',

  'rotate.title': 'Tournez votre appareil',
  'rotate.text': 'Alva se joue en mode paysage.',

  'splash.credit': 'un jeu de {developer}',

  'home.lede': 'Un projet de fan, fait avec cœur.',
  'home.menu': 'Menu principal',
  'home.play': 'Jouer',
  'home.watch': 'Mode spectateur',
  'home.practice': 'Terrain d’entraînement',
  'home.discover': 'Découvrir',
  'home.settings': 'Paramètres',
  'home.help': 'Aide',
  'home.controller': 'Manette',
  'home.download': 'Télécharger',
  'home.credits': 'Crédits',
  'home.creditsRegion': 'Crédits. Faites défiler ou utilisez les flèches haut et bas et les touches Page précédente et Page suivante pour les lire.',
  'home.by': 'Par {developer}',
  'home.whyAlva': 'Pourquoi Alva ?',

  'credits.createdBy': 'Créé par {developer}',
  'credits.original.title': 'Création originale',
  'credits.original.line': 'Conception du jeu, code, interface, logo {title} et illustrations des arènes Désert et Ville par {developer}.',
  'credits.sprites0001.title': 'Source des sprites de #0001',
  'credits.sprites0001.sheet': 'Planche de sprites de Finhj sur DeviantArt',
  'credits.sprites0001.sheetCredits': 'Crédits de la planche : ZetrasBlack, R0B4N',
  'credits.sprites0002.title': 'Source des sprites de #0002',
  'credits.sprites0002.sheet': 'Planche de sprites de thespriteanimations sur DeviantArt',
  'credits.rights.title': 'Droits',
  'credits.rights.ownership': '{developer} n’a pas créé les illustrations originales de personnages et de jeux de tiers, et n’en revendique pas la propriété.',
  'credits.rights.holders': 'Les personnages, les jeux et les propriétés d’origine appartiennent à leurs ayants droit respectifs.',
  'credits.project.title': 'Projet',
  'credits.project.unofficial': 'Projet de fan non officiel.',
  'credits.project.endorsement': 'Aucune affiliation ni approbation n’est sous-entendue.',

  'setup.quickBattle': 'Combat rapide',
  'setup.watch': 'Mode Spectateur',
  'setup.steps': 'Étapes : {name}',
  'step.mode': 'Mode',
  'step.difficulty': 'Difficulté',
  'step.fighter': 'Combattant',
  'step.stage': 'Arène',
  'step.opponent': 'CPU',
  'step.cpu': 'CPU {n}',

  'mode.title': 'Choisir le mode',
  'mode.kicker': 'Jouer',
  'mode.index': 'Mode {index}',
  'mode.quickBattle.description': 'Partie classique ou personnalisée : choisissez une difficulté et votre combattant, puis lancez le combat.',
  'mode.select': 'Choisir',
  'mode.details': 'Détails du mode',

  'quickPlay.title': 'Comment voulez-vous jouer ?',
  'quickPlay.custom.name': 'Partie personnalisée',
  'quickPlay.custom.description': 'Choisissez la difficulté, votre combattant, celui du CPU et l’arène.',
  'quickPlay.regular.name': 'Partie classique',
  'quickPlay.regular.description': 'Choisissez la difficulté et votre combattant. Celui du CPU et l’arène sont tirés au hasard.',

  'difficulty.title': 'Choisir la difficulté',
  'difficulty.group': 'Difficulté',
  'difficulty.current': 'Actuelle',
  'difficulty.card': '{name}, niveau {level} sur {count}',

  'character.title': 'Choisir le combattant',
  'character.cpuTitle': 'Choisir le CPU',
  'watch.cpuTitle': 'Choisir le CPU {n}',
  'roster.grid': 'Liste des combattants',
  'roster.panel': 'Combattants',
  'roster.available': '{name}, disponible',
  'roster.locked': 'Emplacement {num}, verrouillé',
  'roster.statusLocked': 'Verrouillé',
  'roster.statusAvailable': 'Disponible',
  'roster.slot': 'Emplacement {num}',
  'roster.confirm': 'Confirmer le combattant',
  'roster.none': 'Choisissez un combattant',

  'map.title': 'Choisir l’arène',
  'map.stages': 'Arènes',
  'map.available.one': '{n} disponible',
  'map.available.other': '{n} disponibles',
  'map.card': '{name}. {tagline}',
  'map.preview': 'Aperçu de l’arène {name}',
  'map.start': 'Confirmer et lancer le combat',
  'map.watchStart': 'Confirmer et regarder le combat',

  'banner.ready': 'PRÊTS',
  'banner.round': 'ROUND {n}',
  'banner.fight': 'COMBAT',
  'banner.timeOver': 'TEMPS ÉCOULÉ',
  'banner.time': 'TEMPS',
  'banner.void': 'VIDE',
  'banner.ko': 'K.-O.',
  'banner.pointsLevel': 'ÉGALITÉ',
  'banner.overtime': 'PROLONGATION',
  'result.kickerKo': 'K.-O.',
  'result.kickerTime': 'Temps écoulé',
  'result.void': '{loser} est tombé dans le Vide pour le point final.',
  'result.points': 'Le temps est écoulé. Le plus de points l’emporte.',
  'result.time': 'Le temps est écoulé à égalité de points. Le plus petit Point d’éjection l’emporte.',
  'result.kickerOvertime': 'Fin de la prolongation',
  'result.overtimePoints': 'La prolongation est terminée. Le plus de points l’emporte.',
  'result.overtimeLaunchPoint': 'La prolongation est terminée, toujours à égalité de points. Le plus petit Point d’éjection décide.',
  'result.tie': 'Égalité',
  'result.overtimeTie': 'La prolongation est terminée avec les points et le Point d’éjection à égalité.',
  'result.timeTie': 'Le temps est écoulé avec les points et le Point d’éjection à égalité.',
  'result.rematch': 'Revanche',
  'result.changeStage': 'Changer d’arène',
  'side.quickBattle.p1.wins': 'Victoire du joueur 1',
  'side.quickBattle.p1.name': 'Le joueur 1',
  'side.quickBattle.p2.wins': 'Victoire du CPU',
  'side.quickBattle.p2.name': 'Le CPU',
  'side.watch.p1.wins': 'Victoire du CPU 1',
  'side.watch.p1.name': 'Le CPU 1',
  'side.watch.p2.wins': 'Victoire du CPU 2',
  'side.watch.p2.name': 'Le CPU 2',
  'pause.title': 'Pause',
  'pause.resume': 'Reprendre',
  'pause.restart': 'Recommencer le combat',
  'pause.home': 'Retour à l’accueil',
  'confirmHome.title': 'Retourner à l’accueil ?',
  'confirmHome.message': 'Le combat en cours prendra fin et sa progression sera perdue.',
  'confirmHome.confirm': 'Retour à l’accueil',
  'confirmHome.cancel': 'Continuer à jouer',
  'battle.canvas': 'Combat',
  'battle.watchCanvas': 'Combat en mode Spectateur : CPU 1, {p1}, contre CPU 2, {p2}',

  'slot.p1': 'J1',
  'slot.cpu': 'CPU',
  'slot.cpu1': 'CPU 1',
  'slot.cpu2': 'CPU 2',
  'hud.player1': 'Joueur 1',
  'hud.launchPoint': 'Point d’éjection',
  'hud.energy': 'Énergie {value} sur {max}',
  'hud.energyExhausted': 'Énergie épuisée, en recharge : {value} sur {max}',
  'hud.score.one': '{who} : {points} point sur {total}',
  'hud.score.other': '{who} : {points} points sur {total}',
  'hud.pauseGame': 'Mettre en pause',
  'hud.pause': 'Pause',
  'hud.pauseNoLimit': 'Mettre en pause, sans limite de temps',
  'hud.pauseTime': 'Mettre en pause, il reste {left}',
  'hud.pauseOvertime': 'Mettre en pause, prolongation, il reste {left}',
  'hud.round': 'ROUND {n}',
  'hud.overtime': 'PROLONGATION',
  'hud.practiceMenu': 'Menu d’entraînement',
  'unit.minute.one': '{n} minute',
  'unit.minute.other': '{n} minutes',
  'unit.second.one': '{n} seconde',
  'unit.second.other': '{n} secondes',

  'practice.title': 'Terrain d’entraînement',
  'practice.changeFighter': 'Changer de combattant',
  'practice.changeCpu': 'Changer de CPU',
  'practice.enableCpu': 'Activer le CPU',
  'practice.selectCpu': 'Choisir le CPU',
  'practice.disableCpu': 'Désactiver le CPU',
  'practice.return': 'Retour',
  'practice.backToMenu': 'Retour au menu d’entraînement',

  'discover.title': 'Découvrir',
  'discover.sections': 'Sections de Découvrir',
  'discover.fighters': 'Combattants',
  'discover.movement': 'Déplacement',
  'discover.launch': 'Éjection',
  'discover.passives': 'Passifs',
  'discover.movementTitle': 'Déplacement universel',
  'discover.movementList': 'Déplacement universel',
  'discover.launchPointTitle': 'Point d’éjection',
  'discover.baseLaunchTitle': 'Éjection de base',
  'discover.baseLaunchValue': 'Éjection de base {value}',
  'discover.baseLaunchValues': 'Valeurs d’Éjection de base',
  'discover.directionalLaunchTitle': 'Éjection directionnelle',
  'discover.directions': 'Directions d’Éjection directionnelle',
  'discover.difficulty': 'Difficulté',
  'discover.difficultyRating': ({ rating, max }) => `Difficulté : ${rating} ${rating > 1 ? 'étoiles' : 'étoile'} sur ${max}`,
  'discover.unrated': 'Non évalué',
  'discover.noFighters': 'Aucun combattant à afficher pour le moment.',
  'discover.fighterSlot': '{name}, difficulté {rating} sur {max}',
  'discover.playStyle': 'Lire le style de jeu',
  'discover.playStyleTitle': 'Style de jeu',
  'discover.fighter.0001.playStyle': 'Un combattant de contrôle de l’espace et de mise en place, qui gagne en maîtrisant la distance, en attirant ou en repoussant l’adversaire, et en transformant chaque ouverture en éjections puissantes ou en enchaînements de techniques. Rouge et Bleu maximal contrôlent l’espace, tandis que Bleu et le Coup de pied haut changent les ouvertures au corps à corps en éjections. Vide infini ouvre une longue fenêtre de suite, et Violet creux est un coup de grâce lent qui engage lourdement. Infini et le Renvoi récompensent un bon timing défensif. Ses meilleures options exigent un placement soigné, une gestion des temps de recharge et de l’Énergie, une bonne connaissance des affrontements et un timing précis, et une mise en place ratée ou une longue incantation peut le laisser vulnérable.',
  'discover.fighter.0002.playStyle': 'Un combattant de pression offensive et de poursuite aérienne, porté par son élan. Un-deux et Coups de pied rapides offrent une pression au sol simple et directe, tandis qu’Attaque à tête chercheuse, Attaque rebondissante, Attaque tournoyante et Tornade bleue lui permettent d’approcher, de poursuivre et d’éjecter sous plusieurs angles. Tourbillon peut contrôler l’espace et créer des occasions d’éjection, et le Renvoi peut retourner la pression des projectiles contre l’adversaire. Son plan de jeu de base est accessible, mais bien le jouer demande de préserver son élan, de gérer ses utilisations aériennes limitées et ses états de chute libre, de choisir des angles d’approche sûrs et de savoir ne pas trop s’engager face aux Boucliers ou aux fenêtres de punition.',

  'touch.dpad': 'Déplacement',
  'touch.joystick': 'Joystick de déplacement',
  'touch.actions': 'Actions',
  'touch.deflect': 'Renvoi',
  'touch.mouvementLeft': 'Mouvement à gauche',
  'touch.mouvementRight': 'Mouvement à droite',

  'firstRun.title': 'Langue',
  'firstRun.prompt': 'Choisissez votre langue',
  'firstRun.note': 'Vous pourrez la changer plus tard dans les Paramètres.',

  'settings.title': 'Paramètres',
  'settings.close': 'Fermer les paramètres',
  'settings.sections': 'Catégories des paramètres',
  'settings.language': 'Langue',
  'settings.languageNote': 'La langue de tous les menus, libellés et messages.',
  'settings.controls': 'Commandes',
  'settings.mobileControls': 'Commandes tactiles',
  'settings.controlsNote': 'La disposition tactile du Combat rapide et du Terrain d’entraînement. Les commandes au clavier et à la manette ne changent pas.',
  'settings.scheme.joystick': 'Joystick',
  'settings.scheme.classic': 'Boutons classiques',
  'settings.scheme.joystickDesc': 'Utilisez le joystick pour vous déplacer. Touchez un bouton de mouvement une fois pour sprinter à gauche ou à droite.',
  'settings.scheme.classicDesc': 'Maintenez un bouton gauche ou droite pour courir. Touchez une fois un petit bouton de mouvement au-dessus pour sprinter.',
  'settings.customize': 'Personnaliser les commandes tactiles',
  'settings.customizeNote': '{scheme} : déplacez et redimensionnez chaque commande.',
  'settings.customized': 'Disposition personnalisée',
  'settings.combat': 'Combat',
  'settings.combatAssist': 'Assistance au combat',
  'settings.combatAssistDescBeforeEnergy': 'Comble automatiquement un court écart avant une attaque au corps à corps. Ne consomme jamais d’',
  'settings.energy': 'énergie',
  'settings.combatAssistDescAfterEnergy': ' et n’agit jamais sur les attaques à distance.',
  'settings.combatAssistOn': 'Activée',
  'settings.combatAssistOff': 'Désactivée',

  'editor.label': 'Éditeur des commandes tactiles',
  'editor.layout': 'Disposition : {scheme}',
  'editor.hint': 'Faites glisser une commande pour la déplacer. Sélectionnez-en une pour la redimensionner.',
  'editor.keyHint': 'Appuyez sur Entrée ou A pour déplacer une commande avec les flèches ou la croix directionnelle.',
  'editor.none': 'Aucune commande sélectionnée',
  'editor.size': 'Taille',
  'editor.sizeValue': '{percent} %',
  'editor.smaller': 'Réduire',
  'editor.larger': 'Agrandir',
  'editor.reset': 'Rétablir par défaut',
  'editor.done': 'Terminé',
  'editor.moving': '{name} : utilisez les flèches ou la croix directionnelle pour déplacer la commande, puis validez ou revenez en arrière pour terminer.',
  'editor.placed': '{name} en place.',
  'editor.resetDone': 'Disposition par défaut rétablie.',
  'editor.surface': 'Aperçu de l’écran de combat',
};
